language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp
  - npm install --save-dev gulp-uglify
  - npm install --save-dev gulp-react
  - npm install --save-dev gulp-html-replace
  - npm install --save-dev vinyl-source-stream
  - npm install --save-dev browserify
  - npm install --save-dev watchify
  - npm install --save-dev reactify
  - npm install --save-dev gulp-streamify
script: gulp ci